import type { Category, Product } from '@/lib/types'

export const categories: Category[] = [
  {
    name: 'Flooring',
    slug: 'flooring',
    description: 'Vinyl, laminate, engineered hardwood, underlayment, and closeout lots.',
    image: '/supplybird-assets/flooring.png',
    startingPrice: '$0.99 / sq.ft.',
    default_price: 0.99,
    price_unit: 'sq_ft',
    subcategories: ['Vinyl', 'Laminate', 'Engineered hardwood', 'Underlayment'],
  },
  {
    name: 'Doors',
    slug: 'doors',
    description: 'Interior, exterior, patio, and replacement doors for remodels and property turns.',
    image: '/supplybird-assets/windows.png',
    startingPrice: 'Contact for pricing',
    default_price: 0,
    price_unit: 'unit',
    subcategories: ['Interior doors', 'Exterior doors', 'Patio doors', 'Door hardware'],
  },
  {
    name: 'Roofing',
    slug: 'roofing',
    description: 'Architectural shingles and repair-friendly bundle inventory.',
    image: '/supplybird-assets/roofing.png',
    startingPrice: '$22.99 / bundle',
    default_price: 22.99,
    price_unit: 'bundle',
    subcategories: ['Shingles', 'Bundles', 'Repair lots'],
  },
  {
    name: 'Other',
    slug: 'other',
    description: 'Windows, appliances, underlayment, and job-site supply deals.',
    image: '/supplybird-assets/appliances-supplies.png',
    startingPrice: '$36 / roll',
    default_price: 36,
    price_unit: 'roll',
    subcategories: ['Windows', 'Appliances', 'Supplies'],
  },
]

export const availableProducts: Product[] = [
  {
    id: 'home-decorators-akamu-koa-waterproof-vinyl-plank',
    title: 'Home Decorators Collection Akamu Koa Waterproof Vinyl Plank',
    slug: 'home-decorators-akamu-koa-waterproof-vinyl-plank',
    description: 'Warm koa-look waterproof vinyl plank flooring from Home Decorators Collection. Each box includes ten 7 in. x 48 in. planks covering 23.77 sq. ft., with a 5 mm thickness, durable 12 mil wear layer, attached underlayment, and easy click-lock installation. Backed by a limited lifetime residential warranty and a 10-year commercial warranty. A total of 115 boxes provides 2,733.55 sq. ft. of available coverage.',
    category: 'flooring',
    subcategory: 'vinyl',
    price: 30,
    price_unit: 'box',
    coverage_per_box: 23.77,
    coverage_unit: 'sq_ft',
    images: [
      '/product-images/home-decorators-akamu-koa-vinyl-plank-1.jpg',
      '/product-images/home-decorators-akamu-koa-vinyl-plank-2.jpg',
      '/product-images/home-decorators-akamu-koa-vinyl-plank-3.jpg',
      '/product-images/home-decorators-akamu-koa-vinyl-plank-4.jpg',
      '/product-images/home-decorators-akamu-koa-vinyl-plank-5.jpg',
    ],
    in_stock: true,
    featured: true,
    created_at: '2026-08-18T16:00:00.000Z',
    availability_note: '115 Boxes Available · 2,733.55 Sq. Ft. Total',
  },
  {
    id: 'lifeproof-baileys-beach-oak-xl-vinyl-plank',
    title: "LifeProof Bailey's Beach Oak XL Vinyl Plank",
    slug: 'lifeproof-baileys-beach-oak-xl-vinyl-plank',
    description: "High-traffic Bailey's Beach Oak rigid-core waterproof vinyl plank flooring from LifeProof. Features wider, longer XL planks, a durable 22 mil wear layer, attached underlayment, antimicrobial protection, and easy drop-lock installation. Each box covers 25 sq. ft.; 50 boxes provide 1,250 sq. ft. of total available coverage.",
    category: 'flooring',
    subcategory: 'vinyl',
    price: 45,
    price_unit: 'box',
    coverage_per_box: 25,
    coverage_unit: 'sq_ft',
    images: [
      '/product-images/lifeproof-baileys-beach-oak-xl-1.jpg',
      '/product-images/lifeproof-baileys-beach-oak-xl-2.jpg',
      '/product-images/lifeproof-baileys-beach-oak-xl-3.jpg',
      '/product-images/lifeproof-baileys-beach-oak-xl-4.jpg',
    ],
    in_stock: true,
    featured: true,
    created_at: '2026-08-18T13:00:00.000Z',
    availability_note: '50 Boxes Available · 1,250 Sq. Ft. Total',
  },
  {
    id: 'masonite-performance-craftsman-exterior-door',
    title: 'Masonite Performance Craftsman Exterior Door',
    slug: 'masonite-performance-craftsman-exterior-door',
    description: 'Primed white 36 in. x 80 in. Craftsman-style exterior door with decorative glass and the Masonite Performance Door System. Built for a clean entryway upgrade with multi-point security-lock compatibility. Available in both left-hand and right-hand inswing configurations.',
    category: 'doors',
    subcategory: 'exterior-doors',
    price: 390,
    price_unit: 'unit',
    coverage_per_box: null,
    coverage_unit: null,
    images: [
      '/product-images/masonite-performance-craftsman-exterior-door-1.jpg',
      '/product-images/masonite-performance-craftsman-exterior-door-2.jpg',
    ],
    in_stock: true,
    featured: true,
    created_at: '2026-08-18T12:00:00.000Z',
    display_detail: '36 in. x 80 in.',
    availability_note: 'Left- and Right-Hand Inswing Available',
  },
  {
    id: 'mohawk-luxury-vinyl-plank',
    title: 'Mohawk Luxury Vinyl Plank Flooring',
    slug: 'mohawk-luxury-vinyl-plank',
    description: 'Natural oak-look Mohawk luxury vinyl plank flooring with a 5 mm thickness, durable 20 mil wear layer, waterproof construction, and Uniclic locking technology. Each box covers 30.26 sq. ft.',
    category: 'flooring',
    subcategory: 'vinyl',
    price: 45,
    price_unit: 'box',
    coverage_per_box: 30.26,
    coverage_unit: 'sq_ft',
    images: [
      '/product-images/mohawk-luxury-vinyl-plank-1.jpg',
      '/product-images/mohawk-luxury-vinyl-plank-2.jpg',
      '/product-images/mohawk-luxury-vinyl-plank-3.jpg',
    ],
    in_stock: true,
    featured: true,
    created_at: '2026-08-14T14:00:00.000Z',
    availability_note: '130 Boxes Available · 3,933.8 Sq. Ft. Total',
  },
  {
    id: 'stainmaster-lockhart-oak-1079323',
    title: 'Stainmaster Lockhart Oak Waterproof Vinyl Plank',
    slug: 'stainmaster-lockhart-oak-1079323',
    description: 'Gray-brown Lockhart Oak waterproof vinyl plank with Pet Protect, item #1079323. Each box includes eight 7.2 in. x 48.03 in. planks with a 7 mm thickness, 20 mil wear layer, and Greenguard Gold certification.',
    category: 'flooring',
    subcategory: 'vinyl',
    price: 1.59,
    price_unit: 'sq_ft',
    coverage_per_box: 19.22,
    coverage_unit: 'sq_ft',
    images: [
      '/product-images/stainmaster-lockhart-oak-1079323-1.jpg',
      '/product-images/stainmaster-lockhart-oak-1079323-2.jpg',
      '/product-images/stainmaster-lockhart-oak-1079323-3.jpg',
    ],
    in_stock: true,
    featured: true,
    created_at: '2026-08-14T13:00:00.000Z',
  },
  {
    id: 'stainmaster-xl-waterproof-oak-6004585',
    title: 'Stainmaster XL Waterproof Oak Vinyl Plank',
    slug: 'stainmaster-xl-waterproof-oak-6004585',
    description: 'Warm oak-look waterproof vinyl plank, item #6004585. Each box includes five 9.05 in. x 59.75 in. planks with a 7 mm thickness, durable 22 mil wear layer, and Greenguard Gold certification.',
    category: 'flooring',
    subcategory: 'vinyl',
    price: 1.69,
    price_unit: 'sq_ft',
    coverage_per_box: 18.78,
    coverage_unit: 'sq_ft',
    images: ['/product-images/stainmaster-xl-waterproof-oak-6004585-1.jpg', '/product-images/stainmaster-xl-waterproof-oak-6004585-2.jpg'],
    in_stock: true,
    featured: true,
    created_at: '2026-08-14T12:00:00.000Z',
  },
]

export const fallbackProducts: Product[] = [
  ...availableProducts,
  {
    id: 'window-white-vinyl-36',
    title: 'White Vinyl Double-Hung Window',
    slug: 'window-white-vinyl-36',
    description: '36 in. x 48 in. insulated glass replacement window. Good size for rentals and renovation punch lists.',
    category: 'other',
    subcategory: 'windows',
    price: 119,
    price_unit: 'unit',
    coverage_per_box: null,
    coverage_unit: null,
    images: ['/supplybird-assets/windows.png'],
    in_stock: true,
    featured: false,
    created_at: '2026-05-14T12:00:00.000Z',
  },
  {
    id: 'appliance-range-stainless',
    title: 'Stainless Electric Range',
    slug: 'appliance-range-stainless',
    description: '30 in. freestanding electric range, scratch-and-dent tested. Useful for property turns where speed and budget matter.',
    category: 'other',
    subcategory: 'appliances',
    price: 389,
    price_unit: 'unit',
    coverage_per_box: null,
    coverage_unit: null,
    images: ['/supplybird-assets/appliances-supplies.png'],
    in_stock: true,
    featured: false,
    created_at: '2026-05-13T12:00:00.000Z',
  },
  {
    id: 'other-underlayment-roll',
    title: 'Premium Flooring Underlayment Roll',
    slug: 'other-underlayment-roll',
    description: '100 sq.ft. vapor barrier underlayment roll. Common add-on for vinyl, laminate, and engineered flooring estimates.',
    category: 'other',
    subcategory: 'supplies',
    price: 36,
    price_unit: 'roll',
    coverage_per_box: 100,
    coverage_unit: 'sq_ft',
    images: ['/supplybird-assets/appliances-supplies.png'],
    in_stock: true,
    featured: true,
    created_at: '2026-05-12T12:00:00.000Z',
  },
]
