import type { Category, Product } from '@/lib/types'

export const categories: Category[] = [
  {
    name: 'Flooring',
    slug: 'flooring',
    description: 'Vinyl, laminate, engineered hardwood, underlayment, and closeout lots.',
    image: '/supplybird-assets/flooring.png',
    startingPrice: '$0.99 / sq.ft.',
    default_price: 0.99,
    price_unit: 'sq_ft',
    subcategories: ['Vinyl', 'Laminate', 'Engineered hardwood', 'Underlayment'],
  },
  {
    name: 'Decking',
    slug: 'decking',
    description: 'Composite deck boards, fascia, skirting, and porch materials.',
    image: '/supplybird-assets/decking.png',
    startingPrice: '$1.40 / ln.ft.',
    default_price: 1.4,
    price_unit: 'ln_ft',
    subcategories: ['Composite boards', 'Fascia', 'Skirting'],
  },
  {
    name: 'Roofing',
    slug: 'roofing',
    description: 'Architectural shingles and repair-friendly bundle inventory.',
    image: '/supplybird-assets/roofing.png',
    startingPrice: '$22.99 / bundle',
    default_price: 22.99,
    price_unit: 'bundle',
    subcategories: ['Shingles', 'Bundles', 'Repair lots'],
  },
  {
    name: 'Other',
    slug: 'other',
    description: 'Windows, appliances, underlayment, and job-site supply deals.',
    image: '/supplybird-assets/appliances-supplies.png',
    startingPrice: '$36 / roll',
    default_price: 36,
    price_unit: 'roll',
    subcategories: ['Windows', 'Appliances', 'Supplies'],
  },
]

export const fallbackProducts: Product[] = [
  {
    id: 'vinyl-rustic-oak',
    title: 'Rustic Reclaimed Oak Waterproof Vinyl',
    slug: 'vinyl-rustic-oak',
    description: '7 in. waterproof vinyl plank, boxed closeout lot. Good fit for rentals, basements, mudrooms, and light commercial spaces.',
    category: 'flooring',
    subcategory: 'vinyl',
    price: 0.99,
    price_unit: 'sq_ft',
    coverage_per_box: 23.6,
    coverage_unit: 'sq_ft',
    images: ['/supplybird-assets/flooring.png'],
    in_stock: true,
    featured: true,
    created_at: '2026-05-20T12:00:00.000Z',
  },
  {
    id: 'laminate-harbor-gray',
    title: 'Harbor Gray AC4 Laminate',
    slug: 'laminate-harbor-gray',
    description: '12 mm AC4 laminate plank, inspected open pallet. Durable option for bedrooms, offices, and quick-turn remodels.',
    category: 'flooring',
    subcategory: 'laminate',
    price: 1.19,
    price_unit: 'sq_ft',
    coverage_per_box: 20.1,
    coverage_unit: 'sq_ft',
    images: ['/supplybird-assets/flooring.png'],
    in_stock: true,
    featured: true,
    created_at: '2026-05-19T12:00:00.000Z',
  },
  {
    id: 'engineered-maple',
    title: 'Natural Maple Engineered Hardwood',
    slug: 'engineered-maple',
    description: '5 in. engineered maple click-lock flooring for customers who want a warmer finished look than vinyl.',
    category: 'flooring',
    subcategory: 'engineered-hardwood',
    price: 2.85,
    price_unit: 'sq_ft',
    coverage_per_box: 24.8,
    coverage_unit: 'sq_ft',
    images: ['/supplybird-assets/flooring.png'],
    in_stock: false,
    featured: false,
    created_at: '2026-05-18T12:00:00.000Z',
  },
  {
    id: 'decking-coastal-brown',
    title: 'Coastal Brown Composite Deck Board',
    slug: 'decking-coastal-brown',
    description: 'Low-maintenance composite boards in mixed 12 ft., 16 ft., and 20 ft. lengths.',
    category: 'decking',
    subcategory: 'composite-boards',
    price: 1.4,
    price_unit: 'ln_ft',
    coverage_per_box: null,
    coverage_unit: null,
    images: ['/supplybird-assets/decking.png'],
    in_stock: true,
    featured: true,
    created_at: '2026-05-17T12:00:00.000Z',
  },
  {
    id: 'decking-fascia-slate',
    title: 'Slate Composite Fascia / Skirting',
    slug: 'decking-fascia-slate',
    description: '11.25 in. fascia boards for finished stair and perimeter details. New, mixed lengths.',
    category: 'decking',
    subcategory: 'fascia',
    price: 2.1,
    price_unit: 'ln_ft',
    coverage_per_box: null,
    coverage_unit: null,
    images: ['/supplybird-assets/decking.png'],
    in_stock: true,
    featured: false,
    created_at: '2026-05-16T12:00:00.000Z',
  },
  {
    id: 'roofing-charcoal-bundle',
    title: 'Charcoal Architectural Shingles',
    slug: 'roofing-charcoal-bundle',
    description: 'New sealed charcoal architectural shingles. Strong candidate for repairs, garages, sheds, and full roof estimates.',
    category: 'roofing',
    subcategory: 'shingles',
    price: 22.99,
    price_unit: 'bundle',
    coverage_per_box: 33.3,
    coverage_unit: 'sq_ft',
    images: ['/supplybird-assets/roofing.png'],
    in_stock: true,
    featured: true,
    created_at: '2026-05-15T12:00:00.000Z',
  },
  {
    id: 'window-white-vinyl-36',
    title: 'White Vinyl Double-Hung Window',
    slug: 'window-white-vinyl-36',
    description: '36 in. x 48 in. insulated glass replacement window. Good size for rentals and renovation punch lists.',
    category: 'other',
    subcategory: 'windows',
    price: 119,
    price_unit: 'unit',
    coverage_per_box: null,
    coverage_unit: null,
    images: ['/supplybird-assets/windows.png'],
    in_stock: true,
    featured: false,
    created_at: '2026-05-14T12:00:00.000Z',
  },
  {
    id: 'appliance-range-stainless',
    title: 'Stainless Electric Range',
    slug: 'appliance-range-stainless',
    description: '30 in. freestanding electric range, scratch-and-dent tested. Useful for property turns where speed and budget matter.',
    category: 'other',
    subcategory: 'appliances',
    price: 389,
    price_unit: 'unit',
    coverage_per_box: null,
    coverage_unit: null,
    images: ['/supplybird-assets/appliances-supplies.png'],
    in_stock: true,
    featured: false,
    created_at: '2026-05-13T12:00:00.000Z',
  },
  {
    id: 'other-underlayment-roll',
    title: 'Premium Flooring Underlayment Roll',
    slug: 'other-underlayment-roll',
    description: '100 sq.ft. vapor barrier underlayment roll. Common add-on for vinyl, laminate, and engineered flooring estimates.',
    category: 'other',
    subcategory: 'supplies',
    price: 36,
    price_unit: 'roll',
    coverage_per_box: 100,
    coverage_unit: 'sq_ft',
    images: ['/supplybird-assets/appliances-supplies.png'],
    in_stock: true,
    featured: true,
    created_at: '2026-05-12T12:00:00.000Z',
  },
]
